//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IPredict_APP
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class IpredictEntities1 : DbContext
    {
        public IpredictEntities1()
            : base("name=IpredictEntities1")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<League_Year> League_Year { get; set; }
        public virtual DbSet<Match_level> Match_level { get; set; }
        public virtual DbSet<Possibility> Possibilities { get; set; }
        public virtual DbSet<Team_Level> Team_Level { get; set; }
    }
}
