//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IPredict_APP
{
    using System;
    using System.Collections.Generic;
    
    public partial class League_Year
    {
        public int L_uniqe { get; set; }
        public string League_ID { get; set; }
        public string season { get; set; }
        public string LeagueName { get; set; }
        public string Nation { get; set; }
        public string Winner { get; set; }
        public string Top_Scorer { get; set; }
        public string Top_Assister { get; set; }
        public string Top_Saver { get; set; }
        public string Player_of_the_season { get; set; }
        public string F10 { get; set; }
        public string F11 { get; set; }
        public string F12 { get; set; }
        public string F13 { get; set; }
        public string F14 { get; set; }
        public string F15 { get; set; }
        public string F16 { get; set; }
        public string F17 { get; set; }
        public string F18 { get; set; }
        public string F19 { get; set; }
        public string F20 { get; set; }
        public string F21 { get; set; }
        public string F22 { get; set; }
        public string F23 { get; set; }
    }
}
