//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IPredict_APP
{
    using System;
    using System.Collections.Generic;
    
    public partial class Team_Level
    {
        public int T_uniqe { get; set; }
        public string LeaguID { get; set; }
        public Nullable<double> Rank { get; set; }
        public string Season { get; set; }
        public string Team { get; set; }
        public string TEAMID { get; set; }
        public Nullable<double> Played { get; set; }
        public Nullable<double> Win { get; set; }
        public Nullable<double> Draw { get; set; }
        public Nullable<double> Lost { get; set; }
        public Nullable<double> als_Scored { get; set; }
        public Nullable<double> als_Conceded { get; set; }
        public Nullable<double> al_Difference { get; set; }
        public Nullable<double> Points { get; set; }
        public string F14 { get; set; }
        public string F15 { get; set; }
        public string F16 { get; set; }
        public string F17 { get; set; }
    }
}
