//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IPredict_APP
{
    using System;
    using System.Collections.Generic;
    
    public partial class UPredict
    {
        public int predictID { get; set; }
        public string predict { get; set; }
        public string predictStatus { get; set; }
        public string userphone { get; set; }
        public string username { get; set; }
        public Nullable<int> matchid { get; set; }
        public Nullable<int> submitedPoints { get; set; }
    }
}
